version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputsamtemplate.yml
